apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../k8s/deployment.yaml
- ../k8s/service.yaml

namespace: goapp

images:
- name: andersonbatistaferreiracosta/argocd-fullcycle
  newName: andersonbatistaferreiracosta/argocd-fullcycle
  newTag: 0e62fabe781b9e249794668f5f8f49990db56f37
