name: CD 
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: andersonbatistaferreiracosta
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: andersonbatistaferreiracosta/argocd-fullcycle
          tags: ${{ github.sha }}, latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1

      - name: update k8s deployment
        run: |
          cd k8s
          kustomize edit set image andersonbatistaferreiracosta/argocd-fullcycle=andersonbatistaferreiracosta/argocd-fullcycle:${{ github.sha }}
          cat kustomization.yaml
      
      - name: commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git commit -am "Update image version"

      - name: push changes
        uses: ad-m/github-push-action@master